# Generated by Django 3.0.6 on 2020-05-31 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramHome', '0002_auto_20200531_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
