# Generated by Django 3.0.6 on 2020-06-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramHome', '0003_remove_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
