# Generated by Django 3.0.6 on 2020-06-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramHome', '0005_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
