# Generated by Django 3.0.6 on 2020-05-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Bio...📰', max_length=100),
        ),
    ]
